ethless: support state TxCosts
vocdoni/vocdoni-node pull request #473
Opened 2022-02-07 16:24 UTC by jordipainan

2022-02-07 18:16 UTC, NateWilliams2 approved these changes
LGTM, I have one comment though-

Maybe this could be added in a different PR, but could we include `SetTreasurer`, `MintTokens`, and `SetTxCost` functions exposed in Vocone.go? This would be really helpful in testing, i.e. in the vaas-api I can use these to allocate tokens to a faucet account.

I implemented these methods locally to test with:
```
// SetTreasurer configures the vocone treasurer account address
func (vc *Vocone) SetTreasurer(treasurer common.Address) error {
	if err := vc.app.State.SetTreasurer(treasurer); err != nil {
		return err
	}
	vc.app.Commit()
	return nil
}

// MintTokens mints tokens to the given account address
func (vc *Vocone) MintTokens(to common.Address, amount uint64) error {
	if err := vc.app.State.MintBalance(to, amount); err != nil {
		return err
	}
	vc.app.Commit()
	return nil
}

// SetTxCost configures the transaction cost for the given tx type
func (vc *Vocone) SetTxCost(txType models.TxType, cost uint64) error {
	if err := vc.app.State.SetTxCost(txType, cost); err != nil {
		return err
	}
	vc.app.Commit()
	return nil
}
```

I included vc.App.Commit() so that this code can be run synchronously without waiting for the next block to be mined, etc. I understand if this is improper and shouldn't be used though. @jordipainan  and maybe @p4u what do u think?

2022-02-07 18:24 UTC, p4u commented
> I included vc.App.Commit() so that this code can be run synchronously without waiting for the next block to be mined, etc. I understand if this is improper and shouldn't be used though. @jordipainan and maybe @p4u what do u think?

Yes, we can export that methods, I think that makes sense.

Regarding the app.Commit() no way :/ haha

2022-02-07 18:24 UTC, p4u commented
> > I included vc.App.Commit() so that this code can be run synchronously without waiting for the next block to be mined, etc. I understand if this is improper and shouldn't be used though. @jordipainan and maybe @p4u what do u think?
> 
> Yes, we can export that methods, I think that makes sense.
> 
> Regarding the app.Commit() no way :/ haha

Can you send a suggestion so JP can just apply it?

2022-02-07 18:32 UTC, NateWilliams2 commented
> Regarding the app.Commit() no way :/ haha

Thought so but I had to try 😛

2022-02-07 18:38 UTC, NateWilliams2 commented
Interesting, It seems not possible to suggest changes to a file (vocone.go) that's not included in the original PR. I'll push a commit and ask Jordi to review it

2022-02-07 18:39 UTC, NateWilliams2 commented on vocone/vocone.go
> +// SetTreasurer configures the vocone treasurer account address
@jordipainan what do you think of these changes?

2022-02-07 19:08 UTC, p4u requested changes

2022-02-07 19:08 UTC, p4u commented on cmd/vochaintest/vochaintest.go
> +	case "testtxs":
I think we can improve this naming to at least "testTxs", but I'd suggest "testTokenTransactions"

testAllTransactions should take the treasurer key not the oracle (even if its the same, for consistency the function signature should have the correct naming for input variables).

2022-02-07 19:08 UTC, p4u commented on cmd/vochaintest/vochaintest.go
> +	oraclePrivKey string,
that should be treasurerKey

2022-02-07 19:08 UTC, p4u commented on cmd/vochaintest/vochaintest.go
> +	// oracle is also the treasurer
Why this assumption? You really don't know who will call this function

2022-02-07 19:08 UTC, p4u commented on cmd/vochaintest/vochaintest.go
> +func testSetTxCost(mainClient *client.Client, oracleSigner *ethereum.SignKeys) error {
oracleSigner should be treasurerSigner maybe?

2022-02-07 19:08 UTC, p4u commented on dockerfiles/testsuite/start_test.sh
> +[ "$(cat ${testid}1)" == "0" -a "$(cat ${testid}2)" == "0" -a "$(cat ${testid}3)" == "0" -a "$(cat ${testid}4)" == "0" -a "$(cat ${testid}5)" == "0" ] && {
I think its time to break this line

2022-02-07 19:08 UTC, p4u commented on rpcapi/accounthandlers.go
>  	response.Nonce = new(uint32)
Regarding the previous lines (not part of this PR but related):

```
	// account does not exist
	if acc == nil {
		// response ok meaning the account does not exist
		return &response, nil
	}
```
I think we should return an error if the account does not exists.

2022-02-07 19:08 UTC, p4u commented on rpcapi/accounthandlers.go
> +			response.Delegates = append(response.Delegates, common.BytesToAddress(v).String())
Is not the same as doing `fmt.Sprintf("0x%x", v)` ?

2022-02-07 19:08 UTC, p4u commented on rpcapi/accounthandlers.go
> +		// response ok meaning the treasurer does not exist
Same, I think this should be an error

2022-02-07 19:08 UTC, p4u commented on rpcapi/accounthandlers.go
> +	response.EntityID = common.BytesToAddress(t.Address).String()
You can build response here

`response := api.APIresponse { EntityID : ... `

Also I think you don't need to call common.BytesToAddress

2022-02-07 19:08 UTC, p4u commented on vochain/genesis.go
> +         "Tx_SetProcessStatus": 100,
This is breaking for the Genesis.

If a commit modigy the Genesis it should update the genesis version and time and also add a comment to the commit message. Also I think stage genesis should be updated.

2022-02-07 19:08 UTC, p4u commented on vochain/state.go
>  	return addr == tAddr, nil
`return addr == common.BytesToAddress(t.Address), nil` or `bytes.Equal(addr, t.Address)`

2022-02-07 19:08 UTC, p4u commented on vochain/state.go
> +		return err
Ideally all these errors should be wrapped. Else its very hard to identify where it comes from

2022-02-07 19:08 UTC, p4u commented on vochain/state.go
> +	costBytes := [8]byte{}
make is more idiomatic here

2022-02-07 19:08 UTC, p4u commented on vochain/transaction.go
> +	tx := vtx.GetSetTransactionCosts()
vtx should be checked before accessing fields since its a pointer

2022-02-07 19:08 UTC, p4u commented on vochain/transaction.go
> +	if tx.Value <= 0 {
This check removes the possibility to declare a tx with cost 0, I think we should allow that

2022-02-07 19:08 UTC, p4u commented on vochain/transaction.go
> +	if tAddr != sigAddress {
nit: no need to declare tAddr

2022-02-07 19:08 UTC, p4u commented on vochain/transaction.go
> +	if tx.Nonce != treasurer.Nonce {
I think these two last checks should go before extracting the pubkey from the signature (which is the expensive check)

2022-02-07 19:08 UTC, p4u commented on vochain/transaction.go
> +func SetTransactionCostsTxCheck(vtx *models.Tx, txBytes, signature []byte, state *State) (uint64, error) {
Please document all exported methods :)

2022-02-07 19:08 UTC, p4u commented on vochain/types.go
> +func TxCostNameToTxType(key string) models.TxType {
document me!

2022-02-07 20:52 UTC, jordipainan commented
@p4u I cannot comment on your suggestions, regarding the one left (`Is not the same as doing fmt.Sprintf("0x%x", v) ?`) is not the same cause this does not convert to the checksum addr

2022-02-07 21:00 UTC, jordipainan commented
seems the last integration test is not executed, do not merge until solved

2022-02-07 22:38 UTC, p4u approved these changes

2022-02-07 22:38 UTC, p4u commented
great job

2022-02-08 21:40 UTC, NateWilliams2 commented
@p4u @jordipainan I realized a problem with the `SetTreasurer`, `MintTokens`, and `SetTxCost` functions I proposed. These methods all rely on making some changes to the state, so if they are called directly in the code from Vocone.go (without a hacky solution like manually calling `app.State.Save()`), they will have no effect. The next time a block is mined, the state will roll back, and then transactions from the mempool will be applied. The effects of calling these methods from `Vocone.go` will be discarded altogether. It could still be helpful to have these methods in the vocone, but maybe they can add an actual tx to the mempool rather than calling the methods directly. 

I'm actually confused because there are tests in vocdoni-node that seem to rely on calling methods like `app.State.SetTxCost` directly, without committing the state.

2022-02-09 10:37 UTC, jordipainan commented
> 
You're right, I thought you are going to call Save() later.
I also thought that the vocone is just for testing, so you can call Save() later or do not call it if you do not need it. We can talk more about this because maybe I miss some information.

The testing thing you mention is done for setting up the testing easily and does not impact on the actual test itself.

2022-02-09 16:04 UTC, NateWilliams2 commented
> I thought you are going to call Save() later

In this case, we need to expose `app.State.Save` to the vocone as well

2022-02-09 16:06 UTC, NateWilliams2 commented on vocone/vocone.go
> +
```suggestion
func (vc *Vocone) SaveState() error {
	_, err := vc.app.State.Save()
	return err
}
```

2022-02-10 09:24 UTC, p4u approved these changes

2022-02-10 09:24 UTC, p4u commented on vochain/state.go
> +func (v *State) IncrementTreasurerNonce() error {
does this method needs to be exported?

2022-02-10 09:36 UTC, randomshinichi commented
> 

In my original functions, I was calling Save(), I just thought that since the functions you added here didn't have them, you had some solution of your own.

2022-02-10 12:53 UTC, jordipainan commented
@p4u can I merge it ?

2022-02-10 13:16 UTC, p4u commented
> @p4u can I merge it ? I think we can squash everything in one commit

Go ahead, ok to squash

2022-02-10 14:34 UTC, merged