vocli documentation
vocdoni/vocdoni-node pull request #573
Opened 2022-06-21 13:41 UTC by randomshinichi

@altergui @G10h4ck can you check if the README.md explains everything adequately? It's meant for people new to working with the vochain and its concepts, but not new to crypto.

2022-06-27 14:31 UTC, altergui requested changes
disclaimer: i gave this a quick read, didn't actually test the commands described

2022-06-27 14:31 UTC, altergui commented on cmd/vochaintest/vochaintest.go
>  		_, _, _, err = executeCommand(vocli.RootCmd, append([]string{"txcost", "set", aliceKeyPath, "RegisterKey", "50"}, stdArgs...), "", true)
the changes to this file seem out of scope for "vocli documentation", split in a separate PR?

2022-06-27 14:31 UTC, altergui commented on cmd/vocli/commands/helpers.go
> +	return path.Join(home, "keys"), nil
same here, unrelated, split?

2022-06-27 14:31 UTC, altergui commented on cmd/vocli/commands/txcost.go
> +			for _, t := range args {
unrelated, split?

2022-06-27 14:31 UTC, altergui commented on cmd/vocli/README.md
> +One must additionally set an information string when setting an account. Normally an `ipfs://...` info-URI goes here, but this is unvalidated and can thus contain anything.
i'm not a native speaker but "unvalidated" sounds funny to me, why not say "this is currently never validated and can thus contain anything"

2022-07-04 00:02 UTC, randomshinichi commented on cmd/vochaintest/vochaintest.go
>  		_, _, _, err = executeCommand(vocli.RootCmd, append([]string{"txcost", "set", aliceKeyPath, "RegisterKey", "50"}, stdArgs...), "", true)
I was hoping not to have two dependent PRs - oh well here's the other PR

2022-07-04 13:27 UTC, p4u approved these changes

2022-07-04 16:29 UTC, altergui approved these changes

2022-07-04 16:30 UTC, altergui commented
(test was failing due to a race condition in vochaintest, totally unrelated to this PR. took 6 re-runs to make it pass :disappointed: i collected the evidence in https://github.com/vocdoni/vocdoni-node/issues/575 to investigate further)

2022-07-05 00:06 UTC, randomshinichi commented
> (test was failing due to a race condition in vochaintest, totally unrelated to this PR. took 6 re-runs to make it pass disappointed i collected the evidence in #575 to investigate further)

thank you so much! It seems to only happen on the CI servers - on my machine, it seems to be more reliable. Maybe because in a virtualized environment, the processors are more busy. I remember the clocks in Windows Subsystem for Linux would always slowly get out of sync in a matter of days without NTP.

2022-07-05 00:07 UTC, merged