Feature/zk go prover and verifier
vocdoni/vocdoni-node pull request #734
Opened 2022-12-15 17:06 UTC by lucasmenendez

This branch includes a [go-rapidsnark](https://github.com/iden3/go-rapidsnark) abstraction to support the generation and verification of zksnarks anonymous voting weighted census.

It contains a new package at `crypto/zk/prover` that abstracts the go-rapidsnark library enhancing comments and standardizing the inputs and outputs of the functions.

2022-12-15 18:05 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +	// If the inputs its empty or bad formated, it raise a panic. To avoid it,
Typos: 'If the inputs `are` empty or bad `formatted`, it `raises` a panic'

2022-12-15 18:07 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +			var msg = fmt.Sprintf("error parsing provided circuit inputs, it must be a not empty unmarshalled bytes of a json: %v", perr)
i think this variable can be avoided, just put the fmt.Sprint inside errors.New()

2022-12-15 18:08 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +	var inputs map[string]interface{}
normally we declare variables with `foo := bar` instead of using `var foo = bar`

2022-12-15 18:09 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +	if inputs, err = witness.ParseInputs(inputsBytes); err != nil {
`if inputs, err :=`

2022-12-15 18:09 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +		var msg = fmt.Sprintf("error parsing provided circuit inputs, it must be a not empty unmarshalled bytes of a json: %v", err)
this line is too long, also you can avoid declaring the var msg

2022-12-15 18:10 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +	// Instance a go-rapidsnark/witness calculator with the provided wasm []byte
Typo `Instances`

2022-12-15 18:10 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +	if calc, err = witness.NewCircom2WitnessCalculator(wasmBytes, true); err != nil {
`if calc, err :=`

2022-12-15 18:11 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +	if wtns, err = calc.CalculateWTNSBin(inputs, true); err != nil {
In general use `if foo, bar :=` for avoiding carring past errors

2022-12-15 18:11 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +		var msg = fmt.Sprintf("error parsing circuit wasm during calculator instance: %v", err)
In general use foo := bar  when declaring variables

2022-12-15 18:11 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +
unnecessary empty line

2022-12-15 18:12 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +// Prove function generates a verificable proof of the execution of the circuit
typo `verifiable`

2022-12-15 18:13 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +// for the inputs signals using the proving key provided. All the arguments are
typo `input signals`

2022-12-15 18:14 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +// circuit) and SnarkJS (proving zkey). It returns the verificable proof of the
typo `verifiable`

2022-12-15 18:15 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +// Verify function perform a verification of the provided proof and public
typo `performs`

2022-12-15 18:16 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +// into slices of bytes, result of origin files read. It returns and error if
typo 'returns `an` error'

2022-12-15 18:17 UTC, jordipainan commented on crypto/zk/prover/prover_test.go
> +// getExampleFile is a helper function to read local file that is used like test
typo `like a test example`

2022-12-15 18:17 UTC, jordipainan commented on crypto/zk/prover/prover_test.go
> +// example. It rais an error if something was wrong that makes that the current
typo `raises`

2022-12-15 18:18 UTC, jordipainan commented on crypto/zk/prover/prover_test.go
> +// example. It rais an error if something was wrong that makes that the current
this line is difficult to read, rephrase it please

2022-12-15 18:18 UTC, jordipainan commented on crypto/zk/prover/prover_test.go
> +
unnecessary empty line

2022-12-15 18:19 UTC, jordipainan commented on crypto/zk/prover/prover_test.go
> +		wasm        = getExampleFile(t, "./test_files/circuit.wasm")
this var is already declared on line 23, maybe you can make it globally available for the entire file

2022-12-15 18:20 UTC, jordipainan commented on crypto/zk/prover/prover_test.go
> +		t.Error("expected error raised by empty zkey provided, got nil")
I recommend to use the quicktest library for this kind of checks

2022-12-15 18:20 UTC, jordipainan commented on crypto/zk/prover/prover_test.go
> +	// Check a invalid case with empty parameters
typo `an invalid`

2022-12-15 18:23 UTC, jordipainan commented on crypto/zk/prover/prover.go
> +		var msg = fmt.Sprintf("error during zksnark proof generation: %v", err)
it would be nice to have this error messages unified and with constants

2022-12-15 18:23 UTC, jordipainan requested changes
added some comments, good work :)

2022-12-16 09:55 UTC, p4u approved these changes

2022-12-16 10:07 UTC, merged