F/interop/11
vocdoni/vocdoni-node pull request #800
Opened 2023-02-07 10:48 UTC by jordipainan

See https://github.com/vocdoni/interoperability/issues/11

2023-02-07 14:01 UTC, p4u requested changes

2023-02-07 14:01 UTC, p4u commented on api/api_types.go
> +	Syncing          *bool     `json:"syncing,omitempty"`
I'm not sure about declaring all these pointers here. I think ChainInfo is only used by the info endpoint, thus all fields must have a valid value. Is there a specific reason? If not, I'd just declare all of them as standard vars and remove omitempty (I know this is out of the scope here, but I think it is worth to fix it).

2023-02-07 14:01 UTC, p4u commented on api/chain.go
> +	tctx, cancel := context.WithTimeout(context.TODO(), 2*time.Second)
Why a timeout context? Is Genesis() performing an operation that might have a timeout?

2023-02-07 14:01 UTC, p4u commented on api/chain.go
> +	if a.vocapp.Node != nil {
Clients are calling info() several times, I think it is worth it to store the genesis as a static value on the vocapp struct. Then we can access it directly through `a.vocapp.Genesis.GenesisTime`

2023-02-07 14:15 UTC, jordipainan commented on api/api_types.go
> +	Syncing          *bool     `json:"syncing,omitempty"`
The reason is that the other struct fields were declared as pointers and I followed the previous work done.
I assume there were declared as pointers because we want 0/false to be valid values and not ignored in the response, and only ignored if such a specific case is required (by assigning them a nil value).

But ack, going to change the values to get rid of pointers.

2023-02-07 14:15 UTC, jordipainan commented on api/chain.go
> +	tctx, cancel := context.WithTimeout(context.TODO(), 2*time.Second)
Because the method requires a context to be passed.

2023-02-07 14:15 UTC, jordipainan commented on api/chain.go
> +	if a.vocapp.Node != nil {
gotcha, going to add this info to the vocapp struct.

2023-02-07 14:50 UTC, jordipainan commented
Comments addressed, thank you!

2023-02-07 15:07 UTC, p4u approved these changes

2023-02-09 12:48 UTC, p4u commented
Can you fix the compose test and squash?

2023-02-13 14:42 UTC, merged