f/interop/8
vocdoni/vocdoni-node pull request #840
Opened 2023-03-03 10:44 UTC by jordipainan

https://github.com/vocdoni/interoperability/issues/8

2023-03-03 11:07 UTC, altergui requested changes
my code needs fixing, sorry about that

2023-03-03 11:07 UTC, altergui commented on api/chain.go
> +		return fmt.Errorf("%w: %v", ErrCantParseOrgID, err)
fmt.Errorf doesn't really work, this was my fault. i fixed it yesterday and just merged PR #832
 
example
https://github.com/vocdoni/vocdoni-node/pull/832/commits/a5f01b52c6493f10cdd76207cdcf9b2b323663e0#diff-8a1c97a3c76047a21682fceabcf8e05e4fdb9b8909d5e2209ec1fa626e153466L125-L126

new syntax is much prettier, tho :sunglasses: 

`return ErrCantParseOrgID.WithErr(err)`

2023-03-03 11:07 UTC, altergui commented on api/chain.go
> +		return fmt.Errorf("%w: %v", ErrCantParseOrgID, err)
please replace all of the "return fmt.Errorf" inside all *Handler() func

2023-03-03 11:09 UTC, altergui commented on api/elections.go
> +		return fmt.Errorf("%w (%x): %v", ErrMarshalingServerJSONFailed, msg.Data, err)
here you would use Withf instead of WithErr

`return ErrMarshalingServerJSONFailed.Withf("(%x): %v", msg.Data, err)`

2023-03-03 12:15 UTC, lucasmenendez reviewed
Looks good to me!

2023-03-03 12:15 UTC, lucasmenendez commented on api/chain.go
> +	matchingOrganizationIds := a.indexer.EntityList(MaxPageSize, page, organizationId)
Other endpoints return 204 http status code (with an error associated to it) when no results are found. I don't know if this is the expected behaviour here.

2023-03-03 12:15 UTC, lucasmenendez commented on api/chain.go
> +	matchingOrganizationIds := a.indexer.EntityList(MaxPageSize, page, organizationId)
I also have the same doubts about the following endpoints. We have already opened an issue with something similar https://github.com/vocdoni/interoperability/issues/16.

2023-03-06 00:43 UTC, altergui requested changes
i promise i won't request more changes :see_no_evil:

2023-03-06 00:43 UTC, altergui commented on api/elections.go
> +		return ErrMarshalingServerJSONFailed.WithErr(err)
this one is most definitely conceptually wrong, should be ErrCantParseDataAsJSON

2023-03-06 00:43 UTC, altergui commented on api/elections.go
> +		return fmt.Errorf("%w", ErrOrgNotFound)
missed this one, should be `return ErrOrgNotFound` (yes, you can simply return the error, without `With` methods)

2023-03-06 00:43 UTC, altergui commented on api/chain.go
> +		return ErrCantParseOrgID.WithErr(err)
i think this would be `ErrCantParseDataAsJSON.WithErr(err)`?

2023-03-06 09:50 UTC, jordipainan commented on api/chain.go
> +	matchingOrganizationIds := a.indexer.EntityList(MaxPageSize, page, organizationId)
Changed the first one pointed out for now

2023-03-06 10:11 UTC, p4u approved these changes

2023-03-06 11:53 UTC, merged